# For stylua
# https://github.com/JohnnyMorganz/StyLua
syntax = "Lua52"
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 4
quote_style = "ForceDouble"
call_parentheses = "Always"
space_after_function_names = "Never"
collapse_simple_statement = "Never"

[sort_requires]
enabled = true
